{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
spec:
  endpoints:
    - path: {{ .Values.serviceMonitor.path }}
      port: {{ .Values.serviceMonitor.port }}
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
{{- end }}