apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $servicePort := .Values.service.ports }}
    - port: {{ $servicePort.port }}
      targetPort: {{ $servicePort.targetPort }}
      protocol: TCP
      name: {{ $servicePort.name }}
    {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}