---
{{- range $cm := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" $ }}-{{ .name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
{{- with $cm.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
